version: '3.1'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    restart: always
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - cluster.name=testentity
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.zen.minimum_master_nodes=1

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: testentity
